blueprint:
  name: Alarm Clock Media Player (Enhanced)
  description: Plays a local media file when the alarm clock is triggered. Support custom sounds from the event data.
  domain: automation
  input:
    alarm_sensor:
      name: Alarm Status Sensor
      description: The alarm clock status sensor to monitor
      selector:
        entity:
          integration: alarm_clock
          domain: sensor
    media_player:
      name: Media Player
      description: Media player to play the alarm sound
      selector:
        entity:
          domain: media_player

trigger:
  - platform: state
    entity_id: !input alarm_sensor
    to: "triggered"

action:
  - service: media_player.play_media
    target:
      entity_id: !input media_player
    data:
      media_content_id: >
        {% if trigger.to_state.attributes.alarm_sound is defined %}
          media-source://media_source/local/{{ trigger.to_state.attributes.alarm_sound }}
        {% else %}
          media-source://media_source/local/wekker.mp3
        {% endif %}
      media_content_type: audio/mpeg
    metadata:
      title: Alarm Sound
      thumbnail: null
      media_class: music
      children_media_class: null
      navigateIds:
        - {}
        - media_content_type: app
          media_content_id: media-source://media_source

mode: single
